### ISSUE TITLE
Plan for next release - v2.0

### ISSUE THREAD

**Issue by samuelhwilliams** [pallets-eco/flask-admin#2451]
Opening this to think about/plan for the next release, which I propose should encompass:

* [The changes merged after v1.6.1 and up to when flask-admin was moved under pallets-eco](https://github.com/pallets-eco/flask-admin/compare/v1.6.1...7f18761ff4f3cd5e4df2c808d7611d589a549086)

Plus these changes merged since:
* https://github.com/pallets-eco/flask-admin/pull/2397
* https://github.com/pallets-eco/flask-admin/pull/2265
* https://github.com/pallets-eco/flask-admin/pull/2114
* https://github.com/pallets-eco/flask-admin/pull/2416
* https://github.com/pallets-eco/flask-admin/pull/2341
* https://github.com/pallets-eco/flask-admin/pull/2407
* https://github.com/pallets-eco/flask-admin/pull/2321
* https://github.com/pallets-eco/flask-admin/pull/2464

Plus these target changes:
* [x] [Removing python 3.7 support and adding python 3.12](https://github.com/pallets-eco/flask-admin/issues/2449): https://github.com/pallets-eco/flask-admin/pull/2453
* [x] [Removing Flask-BabelEx support and moving back to using Flask-Babel](https://github.com/pallets-eco/flask-admin/issues/2447): https://github.com/pallets-eco/flask-admin/pull/2460
* [x] [Flask `host_matching` support](https://github.com/pallets-eco/flask-admin/issues/1395): https://github.com/pallets-eco/flask-admin/pull/2461
* [x] [Allow configuring FLASK_ADMIN_SWATCH per admin instance](https://github.com/pallets-eco/flask-admin/issues/2423): https://github.com/pallets-eco/flask-admin/pull/2462
* [x] Standardise app.config names: https://github.com/pallets-eco/flask-admin/pull/2472
* [x] SQLAlchemy 2 compatibility (@cjmayo): https://github.com/pallets-eco/flask-admin/pull/2483
* [x] Flask 3 compatibility (@cjmayo)
* [x] WTForms 3 compatibility (@cjmayo)
* [x] Remove bs2 and bs3: https://github.com/pallets-eco/flask-admin/pull/2474
* [x] More clearly define our dependencies/versions: https://github.com/pallets-eco/flask-admin/pull/2476
* [x] Customise and prevent arbitrary user-overrides of `page_size`: https://github.com/pallets-eco/flask-admin/pull/2479
* [x] [Support CSP](https://github.com/pallets-eco/flask-admin/issues/2344): https://github.com/pallets-eco/flask-admin/pull/2480
* [x] https://github.com/pallets-eco/flask-admin/pull/2481
* [ ] Remove any existing `DeprecationWarning`s
* [x] Switch from boto to boto3 for S3FileAdmin: https://github.com/pallets-eco/flask-admin/pull/2552
* [x] Update azure-storage-blob from v3 to v12+
* [x] [Restore mongoengine support, sans flask-mongoengine](https://github.com/pallets-eco/flask-admin/pull/2611)

And potentially any other small PRs we think we can get in fairly easily.

## When the changeset is locked

* [x] review and update documentation for anything that's been missed
* [x] write a changelog entry: https://github.com/pallets-eco/flask-admin/pull/2499/files

---

Because of those last target changes, we'd need to do this as a major version bump.

@aenglander @Abdur-rahmaanJ - thoughts?

**Comment by Abdur-rahmaanJ** [comment]
@samuelhwilliams How about 1.7?

**Comment by samuelhwilliams** [comment]
What makes you suggest 1.7?

I think standard practice would be to assume Semantic Versioning, which says breaking changes should be a major versioning bump (ie 1 to 2). Dropping python 3.7 and dropping flask-babelex are breaking changes, so I think V2 would be the logical step to me.

Happy to hear counter arguments though.

**Comment by hasansezertasan** [comment]
I believe #2407 is suitable for the next release.

**Comment by samuelhwilliams** [comment]
Flask-Babel and host_matching PRs are up. Will leave open for feedback for a few days.

Aiming to do a 2.0.0rc0 release next week ish.

**Comment by samuelhwilliams** [comment]
Right. We have a bunch of stuff merged - I'm thinking of doing a 2.0.0rc0 release, maybe tomorrow. That would mean (in my head) no more feature merges - only bug fix merges - until 2.0.0 proper is released.

Do we think we want to try to get anything else simple/quick in urgently before the rc0 release?

**Comment by samuelhwilliams** [comment]
@cjmayo Have added SQLAlchemy 2/Flask 3/WTForms 3 as target changes for a 2.0.0 release, if you're happy with that? I'm happy to try to help where needed, although it looks like maybe you've got it covered.

**Comment by princerb** [comment]
There are more configuration changes too, like when creating `Admin` instance, so I guess it is fair to think about the next release tagging with 2.0.0 ?

**Comment by samuelhwilliams** [comment]
Would you like to weigh in/mind weighing in on https://github.com/pallets-eco/flask-admin/pull/2476? It deals with dependencies too, specifically making it more explicit what dependencies are required for certain features and what versions we support. It doesn't do much work bumping dependencies, but should make it easier to test+validate dep bumps in the future.

**Comment by princerb** [comment]
About dropping bs3 support.

I don't see bugs or layout issues with the current bs3 theme, while I do on bs4. There are form layout implementations, checkbox positioning, navbar bugs those should have been fixed.

In my opinion, Bootstrap3 is good so far, considering Bootstrap4 fixed & redesigned, I think we should remove bs3 after that? Like later?
Because I also used and applied bs3 mostly, as its template design is implemented well, while bs4 has no a look like bs3's.

**Comment by samuelhwilliams** [comment]
Ok - the target date is obviously slipping a bit, but I think it's useful to get a few more of these things in before doing some kind of pre-release.

Notably:

* [ ] CSP support
* [ ] Decide on whether we deprecate flask-mongoengine, or how we support it if we're keeping it

**Comment by ElLorans** [comment]
Can we have in the docs a suggested approach for considering client's timezone when submitting datetime fields? I am referring to    https://github.com/pallets-eco/flask-admin/issues/1892

**Comment by samuelhwilliams** [comment]
@ElLorans would you like to put up a PR adding some information and/or an example?

**Comment by ElLorans** [comment]
@samuelhwilliams just opened https://github.com/pallets-eco/flask-admin/pull/2502

**Comment by samuelhwilliams** [comment]
Since the changes merged so far for v2.0.0 include a lot of dependency bumps, I think it also makes sense to switch the S3 admin interface over from using `boto` to `boto3`, and the `azure-blob-storage` interface to using azure-storage-blob>=12. So will try to include those as well.

**Comment by pajusmar** [comment]
Thank you for all the hard work on the new release. I noticed that while there are many exciting updates mentioned, there hasn't been any discussion about the state of translations. There was an earlier issue ([#1950](https://github.com/pallets-eco/flask-admin/issues/1950)) that raised concerns about updating translations, and I was wondering if this has been addressed in the latest release or if there are any plans to do so.

**Comment by samuelhwilliams** [comment]
Going to publish v2.0.0a0 shortly - this is an pre-release so would be grateful to anyone able to test it out and see what bugs there may be 🙏 

It's not feature-complete yet necessarily, and I still think it'd be nice to get updates to fileadmin for AWS and Azure in, but I just haven't had time yet. Anyone able to contribute those changes (essentially migrating fileadmin.s3 to use boto3, and updating fileadmin.azure to use azure-storage-blob>=12)

**Comment by samuelhwilliams** [comment]
v2.0.0a0 is now published

**Comment by pajusmar** [comment]
> Hey @pajusmar - it's a good question. I've asked it on the pallets-eco discord to work out what our plan is with translations... 👀

@samuelhwilliams, I saw on Discord that I should submit a pull request to modify translations. Will it make it to 2.0, or are we past the string freeze? I would really like to change one word.

**Comment by samuelhwilliams** [comment]
Nope, by all means put up a PR please. Changes now would still go into V2.0.0 :)

**Comment by LeXofLeviafan** [comment]
Out of curiosity – is there any progress on #1974? (Or at least any information about its causes?)

It just seems kind of bizarre that "View record" & "Edit record" button tooltips are translated, but "Delete record" is not :sweat_smile:

**Comment by ElLorans** [comment]
> Out of curiosity – is there any progress on #1974? (Or at least any information about its causes?)
> 
> It just seems kind of bizarre that "View record" & "Edit record" button tooltips are translated, but "Delete record" is not 😅

Yes that's annoying for sure

**Comment by ElLorans** [comment]
> Out of curiosity – is there any progress on #1974? (Or at least any information about its causes?)
> 
> It just seems kind of bizarre that "View record" & "Edit record" button tooltips are translated, but "Delete record" is not 😅

This is fixed in https://github.com/pallets-eco/flask-admin/pull/2526#issuecomment-2395368678 . @samuelhwilliams can we release 2.0? Are there still DeprecationWarnings?

**Comment by samuelhwilliams** [comment]
I will queue up a 2.0.0a1 soon. I think there's probably still more stuff that makes sense to do for an 'official' v2 release - updating both of the fileadmin implementations for a start.

**Comment by samuelhwilliams** [comment]
I've done a v2.0.0a1 now that includes those changes and compatibility support for wtforms v3.2+

**Comment by samuelhwilliams** [comment]
I do still think it would be good to get in updates for s3/ABS before doing an official release of v2.0.0, but I also am aware that it's taking quite a chunk of time for me to have time for that and there's maybe not a huge amount of appetite from anyone else to add it. :(

**Comment by samuelhwilliams** [comment]
Ok I found time to do boto->boto3, so just azure blob storage to go really 🤞

**Comment by samuelhwilliams** [comment]
that's now available as v2.0.0a2

**Comment by pamelafox** [comment]
@samuelhwilliams Is there an issue about azure blob storage? I can probably tackle that. Just wondering if there were known issues about upgrading, or just general SDK interface changes.

**Comment by samuelhwilliams** [comment]
I'm not aware of any issues specifically - but that is mostly because I haven't looked closely yet. It may well just be SDK interface changes. Would be very grateful if you wanted to tackle it, it's really the last big blocker for an official v2 release, I think 👀 

If there isn't an obvious issue open, please feel free to open one to track it 🙏

**Comment by pamelafox** [comment]
PR for Azure storage upgrade: https://github.com/pallets-eco/flask-admin/pull/2573/files

**Comment by alherm7** [comment]
when are you planning to release 2.0? 😃

**Comment by LeXofLeviafan** [comment]
> when are you planning to release 2.0? 😃

_(checks the thread creation date)_ Somewhere around this year… hopefully 😅

**Comment by samuelhwilliams** [comment]
😭  Yes, this definitely got away from me.

I'd like to get mongoengine support back in (https://github.com/pallets-eco/flask-admin/issues/2541) and azure blob storage (https://github.com/pallets-eco/flask-admin/pull/2573). The latter feels very close, but these two things are essentially just waiting on volunteer/contributor time.

**Comment by alherm7** [comment]
I have a request that could perhaps be considered an addition to a 2.0 release. I hope it is not  too much to ask. Is it possible to generate stubs in pyi files for flask-admin so that it works with mypy? As far as i can tell, mypy can't recognize types for flask-admin currently.

**Comment by Bastian-Kuhn** [comment]
> 😭 Yes, this definitely got away from me.
> 
> I'd like to get mongoengine support back in ([#2541](https://github.com/pallets-eco/flask-admin/issues/2541)) and azure blob storage ([#2573](https://github.com/pallets-eco/flask-admin/pull/2573)) updated. These feel sensible for a new major cut of flask-admin. The latter feels very close, but these two things are essentially just waiting on volunteer/contributor time.

Would also hope to keep the support :)

**Comment by ElLorans** [comment]
> I have a request that could perhaps be considered an addition to a 2.0 release. I hope it is not too much to ask. Is it possible to generate stubs in pyi files for flask-admin so that it works with mypy? As far as i can tell, mypy can't recognize types for flask-admin currently.

Would you have the time to add types directly to flask-admin itself?

**Comment by samuelhwilliams** [comment]
It's optional, but would be nice. Happy for anyone to pick it up

**Comment by samuelhwilliams** [comment]
azure-blob-storage update is now merged after some great work by @pamelafox in https://github.com/pallets-eco/flask-admin/pull/2573 🙏

**Comment by tobni** [comment]
Would there be a possibility of releasing 1.6.x with python 3.12 support? Assuming the mongoengine changes are further ahead.

**Comment by samuelhwilliams** [comment]
That does sound sensible given the amount of time V2 is taking. I'll have a look at getting that again, although I think at this point it's not trivial to publish because there's not a super clean branching point off 1.6 IIRC.

**Comment by LeXofLeviafan** [comment]
If it's a maintenance release specifically for that purpose, you could probably make a branch off the tag commit to cherry pick changes into 🤔

**Comment by ElLorans** [comment]
I might have some capacity next month. Should I tackle DeprecationWarnings or type hints? I don't think I have the expertise to get mongoengine support back in (https://github.com/pallets-eco/flask-admin/issues/2541), which after Azure Blob Storage being merged https://github.com/pallets-eco/flask-admin/pull/2573 looks like the last task.

**Comment by LeXofLeviafan** [comment]
I believe mongoengine is going to be picked up somewhere around the end of this month (unless something comes up).

**Comment by ElLorans** [comment]
> I have a request that could perhaps be considered an addition to a 2.0 release. I hope it is not too much to ask. Is it possible to generate stubs in pyi files for flask-admin so that it works with mypy? As far as i can tell, mypy can't recognize types for flask-admin currently.



> I might have some capacity next month. Should I tackle DeprecationWarnings or type hints? I don't think I have the expertise to get mongoengine support back in ([#2541](https://github.com/pallets-eco/flask-admin/issues/2541)), which after Azure Blob Storage being merged ([#2573](https://github.com/pallets-eco/flask-admin/pull/2573)) looks like the last task.

I opened https://github.com/pallets-eco/flask-admin/pull/2608

**Comment by mreid-tt** [comment]
Hey team — really looking forward to v2.0! I’ve got a few dependencies that hinge on it; for instance, I need to keep `wtforms < 3.2` until the update is out. Hope everything’s going smoothly as you prepare to release it to the community.

**Comment by samuelhwilliams** [comment]
If you are blocked, it is reasonably safe to use the latest alpha release. The only things blocking a full v2 release currently at returning [mongoengine](https://github.com/pallets-eco/flask-admin/pull/2611) support and (optionally) getting type hinting in.

But yes, would definitely be nice to get the full v2 release out soon because we are starting to fall behind on deps :(

**Comment by LeXofLeviafan** [comment]
More specifically, type hints are basically done (other than [a single problem which appears to only have "hacky" solutions](https://github.com/pallets-eco/flask-admin/pull/2608#issuecomment-2866370277)); and the mongo PR has one bug left to take care of (also the guy working on it asked for help with the final check, which I reckon should be done by someone closely familiar with the codebase… probably after that bug is fixed tho 🤷‍♂).

**Comment by adalseno-f** [comment]
Will SQLAlchemy query be updated to the new style?
From:
```python
results = session.query(MyModel).all() # Legacy 1.4 code
```
to
```
stmt = select(MyModel) # 2.0 version
results = session.execute(stmt).scalars().all()
```

**Comment by jake-lester** [comment]
Excited the 2.0 release is on the horizon! Saw some cool bootswatch themes when poking around the source

**Comment by hasansezertasan** [comment]
> Possibly also good to drop python 3.8 and add python 3.13, too.

I just learnt that Python 3.9 will reach EOL [next month](https://peps.python.org/pep-0596/#lifespan) (October 2025).

WDYT about dropping Python 3.9 and adding Python 3.14 too?

[PEP 745 – Python 3.14 Release Schedule](https://peps.python.org/pep-0745/)

**Comment by samuelhwilliams** [comment]
I feel pretty fine about us dropping 3.9, even if it ends up being a week or two before EOL.

We can add 3.14 if 2.0 ends up being after its released. If we do 2.0 before then, I think we're fine to do a 2.x release that brings in 3.14 support.

**Comment by hasansezertasan** [comment]
What about moving [projects.rst](https://github.com/pallets-eco/flask-admin/blob/master/projects.rst) to documentation?

For example: https://ofek.dev/pyapp/latest/users/

**Comment by samuelhwilliams** [comment]
Mongoengine support is back in due to some huge efforts by @Bastian-Kuhn @LeXofLeviafan @ElLorans @hasansezertasan 👏 🙏 

Which leaves us in a good place for moving forward with v2.0.0 I'll do another alpha releases shortly as we might bring in #2639 this small-ish breaking change as well for v2, but then I'll aim to do either a v2 release candidate in the next few days or just a full v2.0.0 live release

**Comment by samuelhwilliams** [comment]
~I also think we should drop sqlalchemy1 support for v2~

e: no

**Comment by samuelhwilliams** [comment]
[v2.0.0a5](https://github.com/pallets-eco/flask-admin/releases/tag/v2.0.0a5) is released now, with the mongoengine (and other) changes 👍

**Comment by samuelhwilliams** [comment]
I didn't make any progress on https://github.com/pallets-eco/flask-admin/issues/2639 - do we want to just go for a full v2 release? I don't think it's worth us blocking a v2 release for any more - we can just add it in a backwards-compatible way.

I'm not sure it's very worth us doing a v2.0.0rc1 or anything - I feel like there hasn't been much feedback on any of the alpha releases and haven't seen many bug reports coming through from them either, so I'm not sure an rc1 would give us more extra assurance.

Anyone listening, feel free to share your opinions on this, but in lieu of any strong objections I will probably aim to do a full v2 releases around this weekend.

**Comment by LeXofLeviafan** [comment]
Isn't that a breaking change? How can it be added in a backwards-compatible way? 🤔

**Comment by Bastian-Kuhn** [comment]
> I'm not sure it's very worth us doing a v2.0.0rc1 or anything - I feel like there hasn't been much feedback on any of the alpha releases and haven't seen many bug reports coming through from them either, so I'm not sure an rc1 would give us more extra assurance.

I started using the v2.0.0a5 and so far, no problems.

**Comment by samuelhwilliams** [comment]
> Isn't that a breaking change? How can it be added in a backwards-compatible way? 🤔

We can make it opt-in instead of new default behaviour (eg `nested_register=False` is the default and you have to turn it on)

**Comment by LeXofLeviafan** [comment]
…Incidentally [Python 3.14 got officially released as a stable version this month (and 3.9 is about to hit end-of-life status)](https://devguide.python.org/versions).

I suggest updating the supported Python versions lists for the project before releasing a new version 🤔

**Comment by samuelhwilliams** [comment]
Yep yep, also realised/(remembered it was flagged further up this thread) this last night - will do that today. Thanks for the nudge.

**Comment by ElLorans** [comment]
Do you want to remove deprecated code as well? Some ObsoleteAttr have been there for 10 years.

**Comment by LeXofLeviafan** [comment]
>  Remove any existing `DeprecationWarning`s

This seems to qualify as well 🤷‍♂️

**Comment by samuelhwilliams** [comment]
Yes it would be nice to remove those things, and I'll gladly look at anyone elses code/PR removing them. I don't think we need to block a 2.0.0 release for them, they can easily come in any time.

I'm managing a few other things and so need to prioritise my time a little, and aware I've held up a 2.0.0 release for a while at this point.

**Comment by samuelhwilliams** [comment]
I've reviewed a lot of the deprecated things and I'm not happy to include those this late in the day, given I've done an rc1 release now.

I'll line them up for a v3 release of flask-admin and we can probably bundle in some wider API/interface changes.

**Comment by samuelhwilliams** [comment]
Scheduling the v2.0.0 release for this Friday 25th October (or the weekend of) :) https://github.com/pallets-eco/flask-admin/pull/2684

**Comment by samuelhwilliams** [comment]
Well it was a long slog, but we got there: https://github.com/pallets-eco/flask-admin/pull/2684

Thank you to everyone who contributed and helped push first this - huge effort getting this over the line 🙇
